// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNq5vVnKYAAOnhA-hbU2_60qR6Yw71K0',
    appId: '1:250300219808:web:65c15aecacdb572a73a4c5',
    messagingSenderId: '250300219808',
    projectId: 'mi-app-flutter-90359',
    authDomain: 'mi-app-flutter-90359.firebaseapp.com',
    storageBucket: 'mi-app-flutter-90359.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBb24cA5YSlFYd34bPu5YHkw1tvtNmkZE',
    appId: '1:250300219808:android:91d808530ded6c9573a4c5',
    messagingSenderId: '250300219808',
    projectId: 'mi-app-flutter-90359',
    storageBucket: 'mi-app-flutter-90359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyB2ze2-HXWMd8sNbg9HAvFgYKO1mmH4',
    appId: '1:250300219808:ios:d7cab3c57f7cf3f173a4c5',
    messagingSenderId: '250300219808',
    projectId: 'mi-app-flutter-90359',
    storageBucket: 'mi-app-flutter-90359.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCyB2ze2-HXWMd8sNbg9HAvFgYKO1mmH4',
    appId: '1:250300219808:ios:d7cab3c57f7cf3f173a4c5',
    messagingSenderId: '250300219808',
    projectId: 'mi-app-flutter-90359',
    storageBucket: 'mi-app-flutter-90359.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnNq5vVnKYAAOnhA-hbU2_60qR6Yw71K0',
    appId: '1:250300219808:web:77220441ba11ef1273a4c5',
    messagingSenderId: '250300219808',
    projectId: 'mi-app-flutter-90359',
    authDomain: 'mi-app-flutter-90359.firebaseapp.com',
    storageBucket: 'mi-app-flutter-90359.firebasestorage.app',
  );
}
